package com.example.tatoebascraper.util;

import org.springframework.stereotype.Component;

import java.util.HashMap;

@Component
public class LangSource {
    public HashMap<String,String> retrieveData(){
        HashMap<String,String> map=new HashMap<String,String>();
        map.put("abq", "Abaza");
        map.put("abk", "Abkhaz");
        map.put("ady", "Adyghe");
        map.put("afh", "Afrihili");
        map.put("afr", "Afrikaans");
        map.put("ain", "Ainu");
        map.put("akl", "Aklanon");
        map.put("sqi", "Albanian");
        map.put("arq", "Algerian Arabic");
        map.put("amh", "Amharic");
        map.put("grc", "Ancient Greek");
        map.put("hbo", "Ancient Hebrew");
        map.put("ara", "Arabic");
        map.put("arg", "Aragonese");
        map.put("hye", "Armenian");
        map.put("asm", "Assamese");
        map.put("aii", "Assyrian Neo-Aramaic");
        map.put("ast", "Asturian");
        map.put("ava", "Avar");
        map.put("awa", "Awadhi");
        map.put("aym", "Aymara");
        map.put("aze", "Azerbaijani");
        map.put("ban", "Balinese");
        map.put("bal", "Baluchi");
        map.put("bam", "Bambara");
        map.put("bjn", "Banjar");
        map.put("bak", "Bashkir");
        map.put("eus", "Basque");
        map.put("bar", "Bavarian");
        map.put("bvy", "Baybayanon");
        map.put("bel", "Belarusian");
        map.put("ben", "Bengali");
        map.put("ber", "Berber");
        map.put("bom", "Berom");
        map.put("bho", "Bhojpuri");
        map.put("bis", "Bislama");
        map.put("brx", "Bodo");
        map.put("bos", "Bosnian");
        map.put("bre", "Breton");
        map.put("bzt", "Brithenig");
        map.put("bul", "Bulgarian");
        map.put("mya", "Burmese");
        map.put("bua", "Buryat");
        map.put("yue", "Cantonese");
        map.put("cat", "Catalan");
        map.put("cay", "Cayuga");
        map.put("ceb", "Cebuano");
        map.put("bcl", "Central Bikol");
        map.put("dtp", "Central Dusun");
        map.put("nch", "Central Huasteca Nahuatl");
        map.put("knc", "Central Kanuri");
        map.put("ckb", "Central Kurdish (Soran\u00ee)");
        map.put("cmo", "Central Mnong");
        map.put("chg", "Chagatai");
        map.put("cha", "Chamorro");
        map.put("cbk", "Chavacano");
        map.put("che", "Chechen");
        map.put("chr", "Cherokee");
        map.put("cpi", "Chinese Pidgin English");
        map.put("chn", "Chinook Jargon");
        map.put("nya", "Chinyanja");
        map.put("cho", "Choctaw");
        map.put("ckt", "Chukchi");
        map.put("chv", "Chuvash");
        map.put("kzj", "Coastal Kadazan");
        map.put("swc", "Congo Swahili");
        map.put("cor", "Cornish");
        map.put("cos", "Corsican");
        map.put("crh", "Crimean Tatar");
        map.put("hrv", "Croatian");
        map.put("cyo", "Cuyonon");
        map.put("cycl", "CycL");
        map.put("ces", "Czech");
        map.put("dan", "Danish");
        map.put("dar", "Dargwa");
        map.put("div", "Dhivehi");
        map.put("drt", "Drents");
        map.put("dng", "Dungan");
        map.put("nld", "Dutch");
        map.put("dws", "Dutton World Speedwords");
        map.put("arz", "Egyptian Arabic");
        map.put("egl", "Emilian");
        map.put("eng", "English");
        map.put("emx", "Erromintxela");
        map.put("myv", "Erzya");
        map.put("epo", "Esperanto");
        map.put("est", "Estonian");
        map.put("evn", "Evenki");
        map.put("ewe", "Ewe");
        map.put("ext", "Extremaduran");
        map.put("fao", "Faroese");
        map.put("hif", "Fiji Hindi");
        map.put("fij", "Fijian");
        map.put("fin", "Finnish");
        map.put("fra", "French");
        map.put("fry", "Frisian");
        map.put("fur", "Friulian");
        map.put("gaa", "Ga");
        map.put("gag", "Gagauz");
        map.put("glg", "Galician");
        map.put("gan", "Gan Chinese");
        map.put("gbm", "Garhwali");
        map.put("kat", "Georgian");
        map.put("deu", "German");
        map.put("aln", "Gheg Albanian");
        map.put("gil", "Gilbertese");
        map.put("got", "Gothic");
        map.put("ell", "Greek");
        map.put("kal", "Greenlandic");
        map.put("gos", "Gronings");
        map.put("gcf", "Guadeloupean Creole French");
        map.put("grn", "Guarani");
        map.put("ngu", "Guerrero Nahuatl");
        map.put("guj", "Gujarati");
        map.put("afb", "Gulf Arabic");
        map.put("hat", "Haitian Creole");
        map.put("hak", "Hakka Chinese");
        map.put("hau", "Hausa");
        map.put("haw", "Hawaiian");
        map.put("heb", "Hebrew");
        map.put("hil", "Hiligaynon");
        map.put("mrj", "Hill Mari");
        map.put("hin", "Hindi");
        map.put("mik", "Hitchiti");
        map.put("mww", "Hmong Daw (White)");
        map.put("hnj", "Hmong Njua (Green)");
        map.put("hoc", "Ho");
        map.put("hun", "Hungarian");
        map.put("hrx", "Hunsrik");
        map.put("iba", "Iban");
        map.put("isl", "Icelandic");
        map.put("ido", "Ido");
        map.put("ibo", "Igbo");
        map.put("ilo", "Ilocano");
        map.put("ind", "Indonesian");
        map.put("izh", "Ingrian");
        map.put("inh", "Ingush");
        map.put("igs", "Interglossa");
        map.put("ina", "Interlingua");
        map.put("ile", "Interlingue");
        map.put("ike", "Inuktitut");
        map.put("acm", "Iraqi Arabic");
        map.put("gle", "Irish");
        map.put("tts", "Isan");
        map.put("ita", "Italian");
        map.put("jam", "Jamaican Patois");
        map.put("jpn", "Japanese");
        map.put("jav", "Javanese");
        map.put("tmr", "Jewish Babylonian Aramaic");
        map.put("jpa", "Jewish Palestinian Aramaic");
        map.put("cjy", "Jin Chinese");
        map.put("jdt", "Juhuri (Judeo-Tat)");
        map.put("quc", "K&#039;iche&#039;");
        map.put("kbd", "Kabardian");
        map.put("kab", "Kabyle");
        map.put("xal", "Kalmyk");
        map.put("kam", "Kamba");
        map.put("kan", "Kannada");
        map.put("pam", "Kapampangan");
        map.put("krc", "Karachay-Balkar");
        map.put("kaa", "Karakalpak");
        map.put("xqa", "Karakhanid");
        map.put("krl", "Karelian");
        map.put("kas", "Kashmiri");
        map.put("csb", "Kashubian");
        map.put("kaz", "Kazakh");
        map.put("kek", "Kekchi (Q&#039;eqchi&#039;)");
        map.put("mfa", "Kelantan-Pattani Malay");
        map.put("kxi", "Keningau Murut");
        map.put("kjh", "Khakas");
        map.put("klj", "Khalaj");
        map.put("kha", "Khasi");
        map.put("khm", "Khmer");
        map.put("kin", "Kinyarwanda");
        map.put("run", "Kirundi");
        map.put("tlh", "Klingon");
        map.put("ksh", "K\u00f6lsch");
        map.put("koi", "Komi-Permyak");
        map.put("kpv", "Komi-Zyrian");
        map.put("gom", "Konkani (Goan)");
        map.put("kor", "Korean");
        map.put("avk", "Kotava");
        map.put("kum", "Kumyk");
        map.put("fkv", "Kven Finnish");
        map.put("kir", "Kyrgyz");
        map.put("ldn", "L\u00e1adan");
        map.put("lld", "Ladin");
        map.put("lad", "Ladino");
        map.put("lbe", "Lak");
        map.put("lkt", "Lakota");
        map.put("lao", "Lao");
        map.put("ltg", "Latgalian");
        map.put("lat", "Latin");
        map.put("lvs", "Latvian");
        map.put("lzz", "Laz");
        map.put("lez", "Lezgi");
        map.put("ayl", "Libyan Arabic");
        map.put("lij", "Ligurian");
        map.put("lim", "Limburgish");
        map.put("lin", "Lingala");
        map.put("lfn", "Lingua Franca Nova");
        map.put("lzh", "Literary Chinese");
        map.put("lit", "Lithuanian");
        map.put("liv", "Livonian");
        map.put("jbo", "Lojban");
        map.put("lmo", "Lombard");
        map.put("lou", "Louisiana Creole");
        map.put("nds", "Low German (Low Saxon)");
        map.put("dsb", "Lower Sorbian");
        map.put("lug", "Luganda");
        map.put("lut", "Lushootseed");
        map.put("ltz", "Luxembourgish");
        map.put("mkd", "Macedonian");
        map.put("mad", "Madurese");
        map.put("bfz", "Mahasu Pahari");
        map.put("mai", "Maithili");
        map.put("mlg", "Malagasy");
        map.put("zsm", "Malay");
        map.put("zlm", "Malay (Vernacular)");
        map.put("mal", "Malayalam");
        map.put("mlt", "Maltese");
        map.put("mgm", "Mambae");
        map.put("mnc", "Manchu");
        map.put("cmn", "Mandarin Chinese");
        map.put("glv", "Manx");
        map.put("mri", "Maori");
        map.put("mar", "Marathi");
        map.put("mah", "Marshallese");
        map.put("mhr", "Meadow Mari");
        map.put("mni", "Meitei");
        map.put("mic", "Mi&#039;kmaq");
        map.put("enm", "Middle English");
        map.put("frm", "Middle French");
        map.put("pal", "Middle Persian (Pahlavi)");
        map.put("nan", "Min Nan Chinese");
        map.put("min", "Minangkabau");
        map.put("xmf", "Mingrelian");
        map.put("mwl", "Mirandese");
        map.put("moh", "Mohawk");
        map.put("mdf", "Moksha");
        map.put("mnw", "Mon");
        map.put("mon", "Mongolian");
        map.put("mnr", "Mono (USA)");
        map.put("mfe", "Morisyen");
        map.put("ary", "Moroccan Arabic");
        map.put("mus", "Muskogee (Creek)");
        map.put("nst", "Naga (Tangshang)");
        map.put("nah", "Nahuatl");
        map.put("nnb", "Nande");
        map.put("nau", "Nauruan");
        map.put("nav", "Navajo");
        map.put("nap", "Neapolitan");
        map.put("npi", "Nepali");
        map.put("new", "Newari");
        map.put("ngt", "Ngeq ");
        map.put("fuv", "Nigerian Fulfulde");
        map.put("niu", "Niuean");
        map.put("nog", "Nogai");
        map.put("frr", "North Frisian");
        map.put("apc", "North Levantine Arabic");
        map.put("max", "North Moluccan Malay");
        map.put("hdn", "Northern Haida");
        map.put("kmr", "Northern Kurdish (Kurmanc\u00ee)");
        map.put("sme", "Northern Sami");
        map.put("kiu", "Northern Zaza (Kirmanjki)");
        map.put("nob", "Norwegian Bokm\u00e5l");
        map.put("nno", "Norwegian Nynorsk");
        map.put("nov", "Novial");
        map.put("nus", "Nuer");
        map.put("iii", "Nuosu");
        map.put("nys", "Nyungar");
        map.put("ood", "O&#039;odham");
        map.put("oci", "Occitan");
        map.put("ori", "Odia (Oriya)");
        map.put("oji", "Ojibwe");
        map.put("ryu", "Okinawan");
        map.put("oar", "Old Aramaic");
        map.put("orv", "Old East Slavic");
        map.put("ang", "Old English");
        map.put("fro", "Old French");
        map.put("ofs", "Old Frisian");
        map.put("non", "Old Norse");
        map.put("prg", "Old Prussian");
        map.put("osx", "Old Saxon");
        map.put("osp", "Old Spanish");
        map.put("tpw", "Old Tupi");
        map.put("otk", "Old Turkish");
        map.put("nlv", "Orizaba Nahuatl");
        map.put("oss", "Ossetian");
        map.put("ota", "Ottoman Turkish");
        map.put("pfl", "Palatine German");
        map.put("pau", "Palauan");
        map.put("pli", "Pali");
        map.put("pag", "Pangasinan");
        map.put("pap", "Papiamento");
        map.put("pus", "Pashto");
        map.put("pdc", "Pennsylvania German");
        map.put("pes", "Persian");
        map.put("phn", "Phoenician");
        map.put("pcd", "Picard");
        map.put("pms", "Piedmontese");
        map.put("ppl", "Pipil");
        map.put("crk", "Plains Cree");
        map.put("pol", "Polish");
        map.put("por", "Portuguese");
        map.put("fuc", "Pulaar");
        map.put("pan", "Punjabi (Eastern)");
        map.put("pnb", "Punjabi (Western)");
        map.put("qxq", "Qashqai");
        map.put("que", "Quechua");
        map.put("qya", "Quenya");
        map.put("rap", "Rapa Nui");
        map.put("rel", "Rendille");
        map.put("rhg", "Rohingya");
        map.put("rom", "Romani");
        map.put("ron", "Romanian");
        map.put("roh", "Romansh");
        map.put("rue", "Rusyn");
        map.put("smo", "Samoan");
        map.put("sgs", "Samogitian");
        map.put("sag", "Sango");
        map.put("san", "Sanskrit");
        map.put("sat", "Santali");
        map.put("skr", "Saraiki");
        map.put("srd", "Sardinian");
        map.put("stq", "Saterland Frisian");
        map.put("sco", "Scots");
        map.put("gla", "Scottish Gaelic");
        map.put("srp", "Serbian");
        map.put("tsn", "Setswana");
        map.put("crs", "Seychellois Creole");
        map.put("wuu", "Shanghainese");
        map.put("sna", "Shona");
        map.put("shs", "Shuswap");
        map.put("scn", "Sicilian");
        map.put("szl", "Silesian");
        map.put("sjn", "Sindarin");
        map.put("snd", "Sindhi");
        map.put("sin", "Sinhala");
        map.put("slk", "Slovak");
        map.put("slv", "Slovenian");
        map.put("som", "Somali");
        map.put("ajp", "South Levantine Arabic");
        map.put("alt", "Southern Altai");
        map.put("hax", "Southern Haida");
        map.put("sdh", "Southern Kurdish");
        map.put("sma", "Southern Sami");
        map.put("sot", "Southern Sotho");
        map.put("laa", "Southern Subanen");
        map.put("diq", "Southern Zaza (Dimli)");
        map.put("spa", "Spanish");
        map.put("srn", "Sranan Tongo");
        map.put("zgh", "Standard Moroccan Tamazight");
        map.put("sux", "Sumerian");
        map.put("sun", "Sundanese");
        map.put("swg", "Swabian");
        map.put("swh", "Swahili");
        map.put("ssw", "Swazi");
        map.put("swe", "Swedish");
        map.put("gsw", "Swiss German");
        map.put("syc", "Syriac");
        map.put("shy", "Tachawit");
        map.put("mvv", "Tagal Murut");
        map.put("tgl", "Tagalog");
        map.put("thv", "Tahaggart Tamahaq");
        map.put("tah", "Tahitian");
        map.put("tgk", "Tajik");
        map.put("tzl", "Talossan");
        map.put("tly", "Talysh");
        map.put("tam", "Tamil");
        map.put("rif", "Tarifit");
        map.put("shi", "Tashelhit");
        map.put("tat", "Tatar");
        map.put("tel", "Telugu");
        map.put("tmw", "Temuan");
        map.put("tet", "Tetun");
        map.put("tha", "Thai");
        map.put("bod", "Tibetan");
        map.put("tig", "Tigre");
        map.put("tir", "Tigrinya");
        map.put("tpi", "Tok Pisin");
        map.put("tkl", "Tokelauan");
        map.put("tok", "Toki Pona");
        map.put("toi", "Tonga (Zambezi)");
        map.put("ton", "Tongan");
        map.put("tso", "Tsonga");
        map.put("tuk", "Turkmen");
        map.put("tvl", "Tuvaluan");
        map.put("tyv", "Tuvinian");
        map.put("aoz", "Uab Meto");
        map.put("udm", "Udmurt");
        map.put("ukr", "Ukrainian");
        map.put("umb", "Umbundu");
        map.put("hsb", "Upper Sorbian");
        map.put("urd", "Urdu");
        map.put("urh", "Urhobo");
        map.put("uig", "Uyghur");
        map.put("uzb", "Uzbek");
        map.put("vec", "Venetian");
        map.put("vep", "Veps");
        map.put("vie", "Vietnamese");
        map.put("vol", "Volap\u00fck");
        map.put("vro", "V\u00f5ro");
        map.put("wln", "Walloon");
        map.put("war", "Waray");
        map.put("guc", "Wayuu");
        map.put("cym", "Welsh");
        map.put("wol", "Wolof");
        map.put("xho", "Xhosa");
        map.put("hsn", "Xiang Chinese");
        map.put("sah", "Yakut");
        map.put("yid", "Yiddish");
        map.put("yor", "Yoruba");
        map.put("yua", "Yucatec Maya");
        map.put("zza", "Zaza");
        map.put("zea", "Zeelandic");
        map.put("zul", "Zulu");
        return map;
    }
}
